"""Cookie handling — converts browser-extension JSON exports into the
Netscape cookies.txt format that yt-dlp accepts.

YouTube throttles unauthenticated downloads to ~1 KB/s. Authenticated
downloads using real browser cookies are not throttled. This module
makes it easy to use a one-time cookie export instead of fighting
the `--cookies-from-browser` lock-file issue when Chrome is running.

Drop a `www.youtube.com_cookies.json` file (exported by "Get cookies.txt
LOCALLY", "Cookie-Editor", etc.) in the repo root or in
~/.twdt-video-bot/ and it will be auto-discovered + converted on use.
"""

import json
import os
import tempfile
from pathlib import Path
from typing import Optional

NETSCAPE_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# This file was generated by twdt_video_bot from a JSON cookie export.\n"
    "\n"
)


def find_cookies_file() -> Optional[Path]:
    """Look in standard locations for a cookies file (JSON or Netscape)."""
    repo_root = Path(__file__).parent.parent.parent
    candidates = [
        repo_root / "www.youtube.com_cookies.json",
        repo_root / "cookies.json",
        repo_root / "cookies.txt",
        Path.home() / ".twdt-video-bot" / "www.youtube.com_cookies.json",
        Path.home() / ".twdt-video-bot" / "cookies.json",
        Path.home() / ".twdt-video-bot" / "cookies.txt",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def json_to_netscape(json_path: Path) -> str:
    """Convert a JSON cookie export to Netscape cookies.txt format text.

    Handles the common browser-extension export shape:
    [{"domain": ".youtube.com", "name": "...", "value": "...",
      "path": "/", "secure": true, "expirationDate": 1234567890, ...}, ...]
    """
    with open(json_path, "r", encoding="utf-8") as f:
        cookies = json.load(f)

    lines = [NETSCAPE_HEADER]
    for c in cookies:
        domain = c.get("domain", "")
        if not domain:
            continue
        # include_subdomains flag: TRUE if domain starts with "."
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # Session cookies have no expiration; use 0
        expiration = int(c.get("expirationDate", 0))
        name = c.get("name", "")
        value = c.get("value", "")
        if not name:
            continue
        lines.append(
            f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n"
        )
    return "".join(lines)


def ensure_netscape_cookies() -> Optional[Path]:
    """Find a cookies file, convert if needed, return a Netscape cookies.txt path.

    Returns None if no cookies file found — caller should fall back to
    unauthenticated (slow) downloads.
    """
    src = find_cookies_file()
    if src is None:
        return None

    if src.suffix.lower() == ".txt":
        # Already in Netscape format
        return src

    # JSON — convert to a temp Netscape file next to the source
    out = src.with_suffix(".txt")
    try:
        content = json_to_netscape(src)
        out.write_text(content, encoding="utf-8")
        return out
    except Exception as e:
        print(f"[cookies] failed to convert {src}: {e}")
        return None
